title: Reese Levine
url: http://dev.reeselevine.me:4000/
author:
    name: Reese Levine
    email: reeselevine@yahoo.com
    github: reeselevine
    twitter: reeselevine
exclude:
    [Gemfile, Gemfile.lock]
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: "blog"
    values:
      layout: blog
