title: Reese Levine
url: http://reeselevine.me/
image_path: assets/images/
author:
    name: Reese Levine
    email: reeselevine1@gmail.com
    github: reeselevine
    twitter: reeselevine
exclude:
    [Gemfile, Gemfile.lock]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "blog"
    values:
      layout: blog
  - scope:
      path: "cs61c"
    values:
      layout: cs61c
  - scope:
      path: "sarah"
    values:
      layout: sarah
