title: Reese Levine
url: http://dev.reeselevine.me:4000/
image_path: assets/images/
author:
    name: Reese Levine
    email: reeselevine@yahoo.com
    github: reeselevine
    twitter: reeselevine
exclude:
    [Gemfile, Gemfile.lock]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: "blog"
    values:
      layout: blog
